### ISSUE TITLE
Autocomplete Functionality

### ISSUE THREAD

**Issue by greycubesgav** [sproutsocial/inputosaurus-text#1]
In the Autocomplete demo your example page you have a nice drop down appear below the text entry box. 

![autocomplete01](https://f.cloud.github.com/assets/3426859/110719/c7a53bb0-6ad0-11e2-8b17-343bbcdce461.png)

However when I add your autocomplete functionality I just get text saying:
_"1 result is available, use up and down arrow keys to navigate."_

![autocomplete02](https://f.cloud.github.com/assets/3426859/110720/d1b914dc-6ad0-11e2-8041-2712946e8f11.png)

How do I get your drop down?

Thanks
Gavin

**Comment by dansnetwork** [comment]
Is there any way you can reproduce this on jsfiddle.net ?

**Comment by dansnetwork** [comment]
I think you may have been missing the jQuery UI CSS file.
