### ISSUE TITLE
Re-ordering items entered? (saving re-ordered items)

### ISSUE THREAD

**Issue by armababy** [sproutsocial/inputosaurus-text#11]
Hello,

How would one proceed with re-ordering items that has been entered before?
For example if you need to edit line you double click it and then it loses it's position and becomes last entry.

Thanks.
![2014 02 28_12h40m25s](https://f.cloud.github.com/assets/219556/2293009/e1385146-a064-11e3-8b59-7fce74603083.png)
![2014 02 28_12h40m49s](https://f.cloud.github.com/assets/219556/2293010/e1392256-a064-11e3-80ee-bfd1df744d5b.png)

Edit: Actually jQuery UI sortable works fine on the list with exclusion of inputosaurus-required input field for sorting. How would you call re-evaluate of current state of elements?

``` javascript
$('#terms .inputosaurus-container').sortable({
    placeholder: 'ui-state-highlight',
    items: 'li:not(.inputosaurus-required)',
    stop: function( event, ui ) {
        // Update inputosaurus-text value input here | $('#terms').inputosaurus();
    }
});
```

**Comment by dansnetwork** [comment]
One thing you could try would be to split the value of the underlying `<input>`, sort the results, and then put them back together (using your delimiter). After that, refresh the widget.

Ex: if the input value is `'2,1,3'`, split the value (using the delimiter/comma), sort them -> `[1,2,3']`, join them back together -> `['1','2','3'].join(',')` and then reset the value of the `<input>` and refresh the widget.

**Comment by armababy** [comment]
@dansnetwork thanks for tip :)

Sorted it:

``` javascript
        $('#terms_lv .inputosaurus-container, #terms_ru .inputosaurus-container').sortable({
            placeholder: 'ui-state-highlight',
            items: 'li:not(.inputosaurus-required)',
            cancel: 'li:not(.inputosaurus-required) span',
            stop: function( event, ui )
            {
                var output      = [],
                    item_parent = ui.item.parent();

                $.each($('li:not(.inputosaurus-required)', item_parent), function(i, e)
                {
                    output[i] = $('span:first', e).text();
                });

                $('.inputosaurus-input-hidden input', item_parent).val(output.join(';'));
                $('.inputosaurus-input-hidden input', item_parent).inputosaurus('refresh');
            }
        });
```
