### ISSUE TITLE
Better documentation is required

### ISSUE THREAD

**Issue by zackster** [sproutsocial/inputosaurus-text#17]
e.g., https://github.com/sproutsocial/inputosaurus-text could say:

"
1) Include jquery, jqueryui, and inputosaurus.js.. in that order
2) Include bootstrap.css and inputosaurus.css
3) Call $("input").inputosaurus({/\* ... */ })

**Comment by jgable** [comment]
> Include jquery, jqueryui, and inputosaurus.js.. in that order

This should be pretty self apparent.  Inputosaurus depends on jquery ui, and jquery ui depends on jquery.  Seems like a straight forward deduction.

> Include bootstrap.css and inputosaurus.css

This project does not depend on boostrap.css at all.

> Call $("input").inputosaurus({/\* ... */ })

I agree it should probably at least include an example barebones snippet of html on the README that would include this.

**Comment by zackster** [comment]
I found that there is documentation for some of the functionality in the test cases.. but this is not necessarily straightforward for the user.  I figured out instance.refresh() but now I'm trying to find the equivalent of $.change()  .. which is no longer triggered after inputosaurus-ifying the input.

Update: found that I can pass in change as a property to $.inputosaurus

**Comment by jgable** [comment]
Better documentation and examples are available at: http://sproutsocial.github.io/inputosaurus-text/

I've added this as the website link for the project so it now shows up at the top of the project page.
