### ISSUE TITLE
IE9 and IE10 have bad UX

### ISSUE THREAD

**Issue by zackster** [sproutsocial/inputosaurus-text#19]
![ie10-inputosaurus](https://cloud.githubusercontent.com/assets/81474/2770439/7a858e4a-ca5e-11e3-9a4c-a66a541520f2.png)

**Comment by jgable** [comment]
Looks pretty good to me on http://sproutsocial.github.io/inputosaurus-text/.  This is most likely a local CSS issue.

**Comment by getaaron** [comment]
:soccer:
