### ISSUE TITLE
Feature Request: Auto Complete Data From Function (AJAX) Call

### ISSUE THREAD

**Issue by greycubesgav** [sproutsocial/inputosaurus-text#2]
Hi;

I'd like to request a feature that I don't think is currently possible with your code?

I'd like to get the results for the auto complete from an external function call each time.

i.e. I have a large dataset of values that I don't really want to set within the code. I'd like to be able to call an external javascript function to do an ajax call with each letter entered and return the result set dynamically.

Is this possible?

Thanks
Gavin

**Comment by dansnetwork** [comment]
You can pass `autoCompleteSource` a function as you would to the jQuery UI Autocomplete widget: http://api.jqueryui.com/autocomplete/#option-source
