### ISSUE TITLE
If the ul contains values with commas, then it creates different tags for words separated with commas.

### ISSUE THREAD

**Issue by gurungbinod** [sproutsocial/inputosaurus-text#20]
If the source list contains the values with commas, e.g "This is, a value". Then clicking on it creates two different tags [This is ] and [a value]. I want it to a single tag [This is, a value]. Am I doing something wrong or there is issue with the plugin??

**Comment by dansnetwork** [comment]
This has to do with the `inputDelimiters` array (config). One of the defaults is a `,`, but you can change it by passing in your own.
