### ISSUE TITLE
remove the selected values on a button click

### ISSUE THREAD

**Issue by rohgang** [sproutsocial/inputosaurus-text#21]
I am trying to remove all the values selected previously on a button cilck.

I have already tried the solution shown in a issue# "call to reset" which suggest as below:
$('#id').val('');
$("#id").inputosaurus('refresh');

But it gives an error ==>>> 
" cannot call methods on inputosaurus prior to initialization; attempted to call method 'refresh'  ".

If possible then please give a working example for this case.

**Comment by dansnetwork** [comment]
I'm assuming you've instantiated the `<input>` prior to requesting a refresh? Do you have a code example that I could look at?

**Comment by rohgang** [comment]
Yes, Below is the code :
<input type="text" class="form-control login-page-user"
            id="inputId" name="inputId" placeholder="Enter ">

$('#inputId').inputosaurus({
            width : '100%',
            autoCompleteSource : 'searchCP',
            inputDelimiters:[';'],
            outputDelimiter:';',
            activateFinalResult : true,
            change : function(ev) {
                showIt('listsearch3');
            }
        });

function which is called on button click is as below:
function hideMe()
{
$('#inputId').val('');
$("#inputId").inputosaurus('refresh');
}

**Comment by dansnetwork** [comment]
Would you happen to be instantiating prior to DOM ready? It's difficult to troubleshoot with only a partial section of code.

**Comment by rohgang** [comment]
I have tried to put the code in DOM ready part also using $(document).ready(function(){}); also.

Can you please give a working code to handle my case ?

**Comment by dansnetwork** [comment]
Why don't you put what you've got up on http://jsfiddle.net or http://jsbin.com and we can troubleshoot from there?

**Comment by rohgang** [comment]
below is the link of JSfiddle. I have tried to replicate the issue:
http://jsfiddle.net/8ZDzL/11/

You will have to click on the button "change" and expected output is the textbox should be cleared.

**Comment by dansnetwork** [comment]
After a quick look, it appears to be an issue related to the version of jQuery used (http://jsfiddle.net/8ZDzL/12/). I'll have to dig in to see why...

**Comment by rohgang** [comment]
ok, Got it, Thanks for your quick response. How soon can I expect the solution ?

**Comment by dansnetwork** [comment]
Give this one a try: http://jsfiddle.net/8ZDzL/13/
It turns out that there was a mismatch between jQuery and jQueryUI versions in your first example. I've also modified the approach to getting the widget instance when refreshing.

**Comment by rohgang** [comment]
Thanks mate, It worked. I just need to copy all the settings and code change that you have suggested i.e. $("#counterParty").data('uiInputosaurus').refresh(); instead of $("#counterParty").inputosaurus('refresh');

Thank you.

**Comment by dansnetwork** [comment]
No problem!
