### ISSUE TITLE
autosuggest and dialog/modal

### ISSUE THREAD

**Issue by nicogee** [sproutsocial/inputosaurus-text#24]
Hi,

I have a form in a jqueryui dialog window. 
When I hit the enter key to complete from the autosuggest, it takes both my uncompleted word and the complete suggestion and converts them to tags.

**Comment by dansnetwork** [comment]
Is this somewhere where I could take a look at the code? If not, you could throw something up on jsfiddle.net

**Comment by nicogee** [comment]
Here is a live example: http://01o.de/bookmarks/guest

when you click on edit and type "git" in the tag-field, you get "github" as a suggestion. When you hit enter, you end up with "git" and "github".

**Comment by dansnetwork** [comment]
It looks like the HTML structure of jQuery UI's Autocomplete widget menu has changed in more recent versions. This is breaking the `activateFinalResult` feature (when using versions of jQuery UI that are more recent than what's being used on the demo page).

Try editing this code (different line number in the source): https://github.com/sproutsocial/inputosaurus-text/commit/904ca5c5d289efe19a3f109d3f7bb66fb88b9a3f#diff-a7f5c7077d5d2862af16cd4563e5aaecR163

Just add: `...  && !$('.ui-menu-item.ui-state-focus').size()` to see if you can get it to work.

If it does, feel free to make a pull request!

**Comment by nicogee** [comment]
Thank you! It works!
