### ISSUE TITLE
How to handle textbox focusout event?

### ISSUE THREAD

**Issue by srinivas1612** [sproutsocial/inputosaurus-text#28]
I entered tag(characters) without entering any input Delimiters, In this case how to make those characters  as a tag because my end user does n't know about  input Delimiter. For this I want to call click event on textbox focusout but it's not making tags. Can you tell me how to do this. Thanks.

$(document).on("focusout", ".txtCategory,.ui-autocomplete-input", function (e) {
        $(".txtCategory,.ui-autocomplete-input,.inputosaurus-container").click();
  });

**Comment by dansnetwork** [comment]
@srinivas1612, you should be able to set `parseOnBlur` to true.

**Comment by srinivas1612** [comment]
@dansnetwork Thank you very much..
