### ISSUE TITLE
How to fetch values

### ISSUE THREAD

**Issue by IvanPain** [sproutsocial/inputosaurus-text#30]
Hello! It's very useful element!
Unfortunately I haven't  find ways fetch values from this control use php or jquery. I'm new in jquery, could you show me the ways I able to fetch values?

**Comment by dansnetwork** [comment]
@IvanPain this widget is no longer supported, but if you'd like to use it "as is" take a look at https://stackoverflow.com/questions/9656523/jquery-autocomplete-with-callback-ajax-json for an example of how to use XHR requests to populate the internal jQuery autocomplete.
