### ISSUE TITLE
Call to reset data

### ISSUE THREAD

**Issue by cartpauj** [sproutsocial/inputosaurus-text#4]
Great plugin by the way. I'm in need of the ability to reset this as I'm submitting the form via ajax, and after the submission completes I need to reset the form to its original state.

Is it possible to reset this completely without doing a page refresh? If not, can you put something in place to make that possible?

**Comment by dansnetwork** [comment]
You should be able to set the value of the original <input> and then refresh the widget:
`$('#myInput').val('');`
`$('#myInput').inputosaurus('refresh');`

**Comment by cartpauj** [comment]
Genius! Worked a treat, thanks man! This is what I had tried before:

```
          $('#mmania_compose_recipients').val('');
          $('li[data-inputosaurus]').remove();
```
