### ISSUE TITLE
Limit # of Suggestions returned

### ISSUE THREAD

**Issue by cartpauj** [sproutsocial/inputosaurus-text#7]
If it's not possible already, just wondering if there's a way to limit the # of rows that are suggested as the user types?

I'm using this on a site right now with 10,000+ users and as the Admin is typing "a" or "ca" etc. the list of suggestions can nearly kill the browser trying to render itself.

**Comment by cartpauj** [comment]
Found a solution for now. Would be awesome if you could add this in as an Option though so I don't have to hack your core:
`source : function(request, response) {
                        var results = $.ui.autocomplete.filter(widget.options.autoCompleteSource, request.term);
                        response(results.slice(0, 15));
                    },`

**Comment by dansnetwork** [comment]
If you search for `minLength` within the source, you'll see that it's currently set to `1`. You could change it to fit your needs (http://api.jqueryui.com/autocomplete/#option-minLength). I may eventually allow that as a passed-in option.

**Comment by cartpauj** [comment]
Well the minLength is different from what I was asking. minLength limits the number of chars required before the lookup occurs and matches returned. My code above actually limits how many matches are returned after the lookup. For example if I type "car" with 10,000 users to possibly match against, the result can be in the hundreds of returned matches. Right now I am unable to limit the returned results using PHP or SQL unfortunately so I have to do it inside of inputosaurus. The above code is working very well though FYI. Thanks again for the great UI widget though!
